image: atlassian/default-image:latest

pipelines:
  schedules:
    weekly:
      - step:
          name: Build and Push DependencyTrack API Server
          script:
            - export ARTIFACTORY_REGISTRY="$ARTIFACTORY_URL/docker-repo"
            - export IMAGE_NAME="$ARTIFACTORY_REGISTRY/dtrack-apiserver"
            - export IMAGE_TAG="latest"
            - docker build -f Dockerfile.apiserver -t $IMAGE_NAME:$IMAGE_TAG .
            - echo $ARTIFACTORY_API_TOKEN | docker login -u $ARTIFACTORY_USER
              --password-stdin $ARTIFACTORY_URL
            - docker push $IMAGE_NAME:$IMAGE_TAG
            - docker logout $ARTIFACTORY_URL
          services:
            - docker
          after-script:
            - |
              if [ $? -ne 0 ]; then
                echo "Build or push failed"
                exit 1
              fi
